version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-dev
    container_name: club_app
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - REDIS_DB=0
      - REDIS_HOST=redis
      - MEDIA_UPLOAD_URL
      - MEDIA_UPLOAD_CODE
    env_file:
      - club/.env
    restart: always
    volumes:
      - .:/app:delegated # enable hot code reload in debug mode
    depends_on:      
      - redis
      - queue
      - webpack
    ports:
      - "8000:8000"

  queue:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-queue
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - REDIS_DB=0
      - REDIS_HOST=redis
    env_file:
      - club/.env      
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:      
      - redis


#  postgres:
#    image: postgres:14
#    container_name: club_postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=vas3k_club

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: unless-stopped    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  webpack:
    image: node:14-slim
    command: npm run watch
    restart: always
    volumes:
      - .:/app:delegated
    working_dir: /app/frontend



# Uncomment these lines if you want to test the Club bot locally
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-bot
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - REDIS_DB=0
      - REDIS_HOST=redis
    env_file:
        - club/.env
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - club_app
      - redis
      
  cron:
    <<: *app
    command: make docker-run-cron
    container_name: club_cron    
    ports: []

# helpdeskbot:
#    <<: *app
#    command: make docker-run-helpdeskbot
#    container_name: club_help_desk_bot    
#    ports:
#      - "8817:8817"
  

# Uncomment these lines if you want to test the Helpdeskbot locally
#  helpdeskbot:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    command: make docker-run-helpdeskbot
#    environment:
#      - MODE=dev
#      - DEBUG=true
#      - PYTHONUNBUFFERED=1
#      - POSTGRES_DB=vas3k_club
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST=postgres
#      - REDIS_DB=0
#      - REDIS_HOST=redis
#    restart: always
#    volumes:
#      - .:/app:delegated
#    depends_on:
#      - club_app
#      - postgres
#      - redis
